version: "3.3"

services:
    nodejs-app:
        build: 
            context: ./nodejsdocker_app
        container_name: nodejsserver
        hostname: nodejsserver
        ports:
          - "8888:8888"
    
    nginx:
        build:
          context: ./nginxdocker_reverseproxy
        container_name: nginx
        hostname: nginx
        ports:
            - "80:80" 
        depends_on:
            - nodejs-app

